# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rikkola's Journal 
email: toni@rikkola.net 
description: > # this means to ignore newlines until "baseurl:"
  I am a programmer at Red Hat working in the KIE team. Let's see where this blog takes me. 
  I also stream in Twitch with the name eno_dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://twitch.com/eno_deb" # the base hostname & protocol for your site
github_username: rikkola 

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine